version: "3"
volumes:
  var:
  db:

services:
  proxy:
    image: vaem/proxy
    volumes:
      - var:/app/var
    ports:
      - 8000:80
    depends_on:
      - app
      - admin_ui
      - embed_ui

  app:
    image: vaem/asset-manager
    env_file: .env
    environment:
      MONGO_URL: mongodb://mongo:27017/asset-manager
      NODE_ENV: production
      BASE: "${BASE}/api"
      SOURCE_ACCEL_REDIRECT: /uploads
    volumes:
      - var:/app/var
    depends_on:
      - mongo

  encoder:
    image: vaem/encoder
    environment:
      ASSETMANAGER_URL: "http://${ENCODER_TOKEN}@app:5000"

  admin_ui:
    image: vaem/admin-ui
    environment:
      VUE_APP_API_URL: "${BASE}/api"
      VUE_APP_EMBED_URL: "${BASE}/embed"
      BASE_URL: "/admin/"
      WEBPACK_BASE_URL: "admin"

  embed_ui:
    image: vaem/embed-ui
    environment:
      VUE_APP_API_URL: "${BASE}/api"
      BASE_URL: "/embed/"
      WEBPACK_BASE_URL: "embed"

  mongo:
    image: mongo:4.2.0
    volumes:
      - db:/data/db