version: "3"
volumes:
  db:
  var:

services:
  asset-manager:
    depends_on:
      - mongo
    image: vaem/asset-manager
    env_file: .env
    environment:
      - MONGO_URL=mongodb://mongo/app
      - "AUTH_URL=google://${GOOGLE_CLIENT_ID}:${GOOGLE_SECRET}@${GOOGLE_HD}"
      - "BASE=${BASE}/api"
      - "SUBTITLEEDIT_API_URL=http://vaem@subtitleedit:5000"
    volumes:
      - var:/app/var

  mongo:
    image: mongo:5.0.4
    volumes:
      - db:/data/db

  web:
    depends_on:
      - asset-manager
    image: vaem/web
    environment:
      - "API_URL=${BASE}/api"
      - "EMBED_URL=${BASE}/embed"
      - "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}"
    ports:
      - "8080:8080"

  encoder:
    image: vaem/encoder
    environment:
      - ASSETMANAGER_URL=http://asset-manager:5000
    volumes:
      - var:/app/var

  subtitleedit:
    image: vaem/subtitleedit-api
    environment:
      - API_KEY=vaem
