volumes:
  db:
  var:

services:
  asset-manager:
    links:
      - mongo
    depends_on:
      - mongo
    image: vaem/asset-manager
    platform: linux/amd64
    env_file: .env
    environment:
      - MONGO_URL=mongodb://mongo/app
      - "AUTH_URL=google://${GOOGLE_CLIENT_ID}:${GOOGLE_SECRET}@${GOOGLE_HD}"
      - "BASE=${BASE}/api"
      - "SUBTITLEEDIT_API_URL=http://vaem@subtitleedit:5000"
    volumes:
      - var:/app/var

  mongo:
    image: mongo:5.0.4
    volumes:
      - db:/data/db

  web:
    depends_on:
      - asset-manager
    platform: linux/amd64
    image: vaem/web
    environment:
      - "NUXT_PUBLIC_API_URL=${BASE}/api/"
      - "NUXT_PUBLIC_EMBED_URL=${BASE}/embed/"
    ports:
      - "3000:8080"

  encoder:
    image: vaem/encoder
    platform: linux/amd64
    environment:
      - ASSETMANAGER_URL=http://asset-manager:5000
    volumes:
      - var:/app/var

  subtitleedit:
    platform: linux/amd64
    image: vaem/subtitleedit-api
    environment:
      - API_KEY=vaem
